### ISSUE TITLE
Issue-Fix lint

### ISSUE THREAD

**Issue by scdnj** [scdnj/micro-signer-eth#109]
Automated Review Comments
Issues in index.js:
  - (1, 'Line exceeds 80 characters')
  - (1, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
  - (20, 'Hardcoded string found')
  - (21, 'Line exceeds 80 characters')
  - (23, 'Line exceeds 80 characters')
  - (24, 'Line exceeds 80 characters')
  - (31, 'Line exceeds 80 characters')
  - (32, 'Line exceeds 80 characters')
  - (33, 'Line exceeds 80 characters')
  - (41, 'Line exceeds 80 characters')
  - (50, 'Line exceeds 80 characters')
  - (61, 'Line exceeds 80 characters')
  - (61, 'Hardcoded string found')
  - (65, 'Hardcoded string found')
  - (66, 'Line exceeds 80 characters')
Issues in index.ts:
  - (8, 'Line exceeds 80 characters')

**Comment by satokihanada** [comment]
I got it.
