### ISSUE TITLE
Issue-Add benchmark

### ISSUE THREAD

**Issue by scdnj** [scdnj/micro-signer-eth#125]
Automated Review Comments
Issues in package.json:
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (10, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
Issues in test/benchmark.js:
  - (15, 'Line exceeds 80 characters')

**Comment by satomichru** [comment]
I got it.
