### ISSUE TITLE
Issue-Recompile

### ISSUE THREAD

**Issue by scdnj** [scdnj/micro-signer-eth#140]
Automated Review Comments
Issues in index.d.ts:
  - (9, 'Line exceeds 80 characters')
  - (9, 'Hardcoded string found')
Issues in index.js:
  - (2, 'Hardcoded string found')
  - (5, 'Line exceeds 80 characters')
  - (6, 'Line exceeds 80 characters')
  - (25, 'Hardcoded string found')
  - (35, 'Hardcoded string found')
  - (55, 'Hardcoded string found')
  - (60, 'Line exceeds 80 characters')
  - (60, 'Hardcoded string found')
  - (62, 'Hardcoded string found')
  - (64, 'Hardcoded string found')
  - (66, 'Hardcoded string found')
  - (69, 'Hardcoded string found')
  - (71, 'Hardcoded string found')
  - (75, 'Line exceeds 80 characters')
  - (75, 'Hardcoded string found')
  - (76, 'Line exceeds 80 characters')
  - (78, 'Hardcoded string found')
  - (84, 'Line exceeds 80 characters')
  - (88, 'Hardcoded string found')
Issues in tx-validator.ts:
  - (7, 'Hardcoded string found')
  - (9, 'Line exceeds 80 characters')
  - (21, 'Hardcoded string found')

**Comment by satokihanada** [comment]
I got it.
