### ISSUE TITLE
Issue-ESM

### ISSUE THREAD

**Issue by scdnj** [scdnj/micro-signer-eth#144]
Automated Review Comments
Issues in package.json:
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (6, 'Line exceeds 80 characters')
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
  - (10, 'Hardcoded string found')
Issues in test/test.js:
  - (2, 'Hardcoded string found')
  - (34, 'Hardcoded string found')
  - (74, 'Line exceeds 80 characters')
Issues in tsconfig.json:
  - (2, 'Hardcoded string found')
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (9, 'Hardcoded string found')

**Comment by satomichru** [comment]
I got it.
