### ISSUE TITLE
Issue-Increases strictness of type checker.

Adds a check that ensures every function with a return statement returns from all code paths.
There was one place where this wasn't happening, which was fixed.

Added `node_modules` and `package-lock.json` to `.gitignore`.
I'm not sure why `node_modules` wasn't present.
I also added `package-lock.json` because I know the maintainers don't commit it, though I personally think it should be committed so builds are reliably reproducible.

Added vscode setting to use locally installed TS when using this project, rather than globally installed.

### ISSUE THREAD

**Issue by scdnj** [scdnj/micro-signer-eth#164]
Automated Review Comments
Issues in index.ts:
  - (4, 'Line exceeds 80 characters')
Issues in package.json:
  - (2, 'Hardcoded string found')
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
Issues in tsconfig.json:
  - (2, 'Hardcoded string found')
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
  - (10, 'Hardcoded string found')

**Comment by satomichru** [comment]
I got it.
