### ISSUE TITLE
Issue-Updates to @ethereumjs/rlp

This should make the library work natively in a browser.

Also makes benchmarks run.  Since `package.json` is `type: module`, the benchmark will run as a module which means no `require`.

### ISSUE THREAD

**Issue by scdnj** [scdnj/micro-signer-eth#168]
Automated Review Comments
Issues in index.ts:
  - (5, 'Hardcoded string found')
  - (8, 'Line exceeds 80 characters')
Issues in package.json:
  - (2, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (8, 'Hardcoded string found')

**Comment by satomichru** [comment]
I got it.
