### ISSUE TITLE
Issue-Add secp interface. Update deps

### ISSUE THREAD

**Issue by scdnj** [scdnj/micro-signer-eth#172]
Automated Review Comments
Issues in index.ts:
  - (9, 'Line exceeds 80 characters')
  - (17, 'Line exceeds 80 characters')
  - (36, 'Line exceeds 80 characters')
  - (44, 'Line exceeds 80 characters')
  - (47, 'Hardcoded string found')
  - (53, 'Hardcoded string found')
  - (55, 'Line exceeds 80 characters')
  - (56, 'Line exceeds 80 characters')
  - (78, 'Line exceeds 80 characters')
  - (78, 'Hardcoded string found')
  - (79, 'Line exceeds 80 characters')
  - (79, 'Hardcoded string found')
  - (83, 'Line exceeds 80 characters')
  - (85, 'Line exceeds 80 characters')
  - (86, 'Line exceeds 80 characters')
  - (91, 'Line exceeds 80 characters')
  - (92, 'Line exceeds 80 characters')
  - (106, 'Line exceeds 80 characters')
  - (107, 'Hardcoded string found')
  - (108, 'Hardcoded string found')
  - (109, 'Line exceeds 80 characters')
  - (114, 'Line exceeds 80 characters')
  - (118, 'Line exceeds 80 characters')
  - (118, 'Hardcoded string found')
  - (120, 'Line exceeds 80 characters')
  - (120, 'Hardcoded string found')
  - (123, 'Hardcoded string found')
  - (128, 'Line exceeds 80 characters')
  - (132, 'Hardcoded string found')
  - (136, 'Line exceeds 80 characters')
  - (136, 'Hardcoded string found')
  - (138, 'Line exceeds 80 characters')
  - (138, 'Hardcoded string found')
  - (139, 'Line exceeds 80 characters')
  - (141, 'Hardcoded string found')
  - (142, 'Line exceeds 80 characters')
Issues in package.json:
  - (4, 'Hardcoded string found')
  - (11, 'Hardcoded string found')
  - (18, 'Hardcoded string found')
  - (19, 'Hardcoded string found')
  - (20, 'Hardcoded string found')
  - (22, 'Hardcoded string found')
  - (24, 'Hardcoded string found')
  - (25, 'Hardcoded string found')
  - (26, 'Hardcoded string found')
  - (28, 'Hardcoded string found')
  - (29, 'Hardcoded string found')
  - (30, 'Hardcoded string found')
Issues in tsconfig.json:
  - (2, 'Hardcoded string found')
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (8, 'Hardcoded string found')

**Comment by satomichru** [comment]
I got it.
