### ISSUE TITLE
Issue-Fix git url

### ISSUE THREAD

**Issue by scdnj** [scdnj/micro-signer-eth#18]
Automated Review Comments
Issues in package.json:
  - (4, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
  - (11, 'Hardcoded string found')
  - (12, 'Hardcoded string found')

**Comment by satokihanada** [comment]
I got it.
