### ISSUE TITLE
Issue-Bump deps, move build files

### ISSUE THREAD

**Issue by scdnj** [scdnj/micro-signer-eth#180]
Automated Review Comments
Issues in package.json:
  - (4, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
  - (10, 'Hardcoded string found')
  - (11, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
  - (13, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
  - (19, 'Hardcoded string found')
  - (20, 'Hardcoded string found')
  - (23, 'Hardcoded string found')
  - (24, 'Hardcoded string found')
  - (25, 'Hardcoded string found')

**Comment by satomichru** [comment]
I got it.
