### ISSUE TITLE
Issue-Improve isObj check

### ISSUE THREAD

**Issue by scdnj** [scdnj/micro-signer-eth#220]
Automated Review Comments
Issues in index.ts:
  - (14, 'Hardcoded string found')
  - (21, 'Line exceeds 80 characters')
  - (26, 'Line exceeds 80 characters')
  - (26, 'Hardcoded string found')
  - (28, 'Line exceeds 80 characters')
  - (28, 'Hardcoded string found')
  - (35, 'Line exceeds 80 characters')
  - (35, 'Hardcoded string found')
  - (39, 'Line exceeds 80 characters')
  - (39, 'Hardcoded string found')
  - (43, 'Hardcoded string found')
  - (48, 'Line exceeds 80 characters')
  - (50, 'Hardcoded string found')
  - (56, 'Line exceeds 80 characters')
  - (56, 'Hardcoded string found')
  - (60, 'Hardcoded string found')

**Comment by satokihanada** [comment]
I got it.
