### ISSUE TITLE
Issue-Switch package to hybrid common.js-esm

### ISSUE THREAD

**Issue by scdnj** [scdnj/micro-signer-eth#224]
Automated Review Comments
Issues in package-lock.json:
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
  - (10, 'Hardcoded string found')
  - (11, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
  - (17, 'Hardcoded string found')
  - (20, 'Hardcoded string found')
  - (21, 'Hardcoded string found')
  - (25, 'Hardcoded string found')
  - (26, 'Hardcoded string found')
  - (27, 'Line exceeds 80 characters')
  - (27, 'Hardcoded string found')
  - (28, 'Hardcoded string found')
  - (29, 'Hardcoded string found')
  - (31, 'Hardcoded string found')
  - (32, 'Hardcoded string found')
  - (36, 'Hardcoded string found')
  - (37, 'Line exceeds 80 characters')
  - (37, 'Hardcoded string found')
  - (38, 'Line exceeds 80 characters')
  - (38, 'Hardcoded string found')
  - (39, 'Hardcoded string found')
  - (42, 'Hardcoded string found')
  - (43, 'Hardcoded string found')
  - (47, 'Hardcoded string found')
  - (48, 'Line exceeds 80 characters')
  - (48, 'Hardcoded string found')
  - (49, 'Line exceeds 80 characters')
  - (49, 'Hardcoded string found')
  - (50, 'Hardcoded string found')
  - (51, 'Hardcoded string found')
  - (53, 'Hardcoded string found')
  - (54, 'Hardcoded string found')
  - (58, 'Hardcoded string found')
  - (59, 'Line exceeds 80 characters')
  - (59, 'Hardcoded string found')
  - (60, 'Line exceeds 80 characters')
  - (60, 'Hardcoded string found')
  - (61, 'Hardcoded string found')
  - (64, 'Hardcoded string found')
  - (65, 'Line exceeds 80 characters')
  - (65, 'Hardcoded string found')
  - (66, 'Line exceeds 80 characters')
  - (66, 'Hardcoded string found')
  - (67, 'Hardcoded string found')
  - (70, 'Hardcoded string found')
  - (71, 'Hardcoded string found')
  - (72, 'Line exceeds 80 characters')
  - (72, 'Hardcoded string found')
  - (73, 'Hardcoded string found')
  - (74, 'Hardcoded string found')
  - (75, 'Hardcoded string found')
  - (77, 'Hardcoded string found')
  - (78, 'Hardcoded string found')
  - (80, 'Hardcoded string found')
  - (81, 'Hardcoded string found')
  - (85, 'Hardcoded string found')
  - (86, 'Line exceeds 80 characters')
  - (86, 'Hardcoded string found')
  - (87, 'Line exceeds 80 characters')
  - (87, 'Hardcoded string found')
  - (88, 'Hardcoded string found')
  - (89, 'Hardcoded string found')
  - (90, 'Hardcoded string found')
  - (91, 'Hardcoded string found')
  - (93, 'Hardcoded string found')
  - (94, 'Hardcoded string found')
  - (98, 'Hardcoded string found')
  - (100, 'Hardcoded string found')
  - (101, 'Hardcoded string found')
  - (102, 'Line exceeds 80 characters')
  - (102, 'Hardcoded string found')
  - (105, 'Hardcoded string found')
  - (106, 'Line exceeds 80 characters')
  - (106, 'Hardcoded string found')
  - (107, 'Line exceeds 80 characters')
  - (107, 'Hardcoded string found')
  - (108, 'Hardcoded string found')
  - (113, 'Hardcoded string found')
  - (114, 'Line exceeds 80 characters')
  - (114, 'Hardcoded string found')
  - (115, 'Line exceeds 80 characters')
  - (115, 'Hardcoded string found')
  - (118, 'Hardcoded string found')
  - (119, 'Line exceeds 80 characters')
  - (119, 'Hardcoded string found')
  - (120, 'Line exceeds 80 characters')
  - (120, 'Hardcoded string found')
  - (121, 'Hardcoded string found')
  - (124, 'Hardcoded string found')
  - (125, 'Line exceeds 80 characters')
  - (125, 'Hardcoded string found')
  - (126, 'Line exceeds 80 characters')
  - (126, 'Hardcoded string found')
  - (127, 'Hardcoded string found')
  - (129, 'Hardcoded string found')
  - (130, 'Hardcoded string found')
  - (131, 'Hardcoded string found')
  - (132, 'Line exceeds 80 characters')
  - (132, 'Hardcoded string found')
  - (133, 'Hardcoded string found')
  - (135, 'Hardcoded string found')
  - (136, 'Hardcoded string found')
  - (137, 'Line exceeds 80 characters')
  - (137, 'Hardcoded string found')
  - (138, 'Line exceeds 80 characters')
  - (138, 'Hardcoded string found')
  - (139, 'Hardcoded string found')
Issues in package.json:
  - (2, 'Hardcoded string found')
  - (3, 'Hardcoded string found')
  - (4, 'Line exceeds 80 characters')
  - (4, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
  - (22, 'Hardcoded string found')
  - (27, 'Hardcoded string found')
  - (28, 'Hardcoded string found')
  - (29, 'Hardcoded string found')
  - (30, 'Hardcoded string found')
  - (34, 'Hardcoded string found')
  - (36, 'Hardcoded string found')
  - (37, 'Hardcoded string found')
  - (38, 'Hardcoded string found')
  - (40, 'Hardcoded string found')
  - (41, 'Line exceeds 80 characters')
  - (41, 'Hardcoded string found')
  - (42, 'Line exceeds 80 characters')
  - (42, 'Hardcoded string found')
  - (43, 'Hardcoded string found')
  - (44, 'Hardcoded string found')
  - (45, 'Hardcoded string found')
Issues in src/formatters.ts:
  - (13, 'Line exceeds 80 characters')
  - (46, 'Line exceeds 80 characters')
  - (54, 'Line exceeds 80 characters')
  - (55, 'Line exceeds 80 characters')
  - (56, 'Line exceeds 80 characters')
  - (57, 'Line exceeds 80 characters')
  - (71, 'Line exceeds 80 characters')
  - (87, 'Line exceeds 80 characters')
  - (95, 'Line exceeds 80 characters')
  - (100, 'Line exceeds 80 characters')
  - (114, 'Hardcoded string found')
  - (117, 'Hardcoded string found')
  - (122, 'Hardcoded string found')
  - (125, 'Line exceeds 80 characters')
  - (125, 'Hardcoded string found')
Issues in src/index.ts:
  - (9, 'Line exceeds 80 characters')
  - (16, 'Line exceeds 80 characters')
  - (19, 'Line exceeds 80 characters')
  - (31, 'Line exceeds 80 characters')
  - (32, 'Line exceeds 80 characters')
  - (56, 'Hardcoded string found')
  - (63, 'Hardcoded string found')
  - (69, 'Hardcoded string found')
  - (71, 'Hardcoded string found')
  - (83, 'Line exceeds 80 characters')
  - (83, 'Hardcoded string found')
  - (86, 'Hardcoded string found')
  - (87, 'Hardcoded string found')
  - (91, 'Hardcoded string found')
  - (92, 'Hardcoded string found')
  - (105, 'Hardcoded string found')
  - (106, 'Hardcoded string found')
  - (112, 'Line exceeds 80 characters')
  - (113, 'Line exceeds 80 characters')
  - (132, 'Line exceeds 80 characters')
  - (135, 'Hardcoded string found')
  - (136, 'Hardcoded string found')
  - (138, 'Hardcoded string found')
  - (150, 'Line exceeds 80 characters')
  - (154, 'Line exceeds 80 characters')
  - (154, 'Hardcoded string found')
  - (156, 'Line exceeds 80 characters')
  - (156, 'Hardcoded string found')
  - (158, 'Line exceeds 80 characters')
  - (158, 'Hardcoded string found')
  - (160, 'Line exceeds 80 characters')
  - (160, 'Hardcoded string found')
  - (161, 'Line exceeds 80 characters')
  - (161, 'Hardcoded string found')
  - (163, 'Hardcoded string found')
  - (165, 'Hardcoded string found')
  - (172, 'Line exceeds 80 characters')
  - (172, 'Hardcoded string found')
  - (176, 'Hardcoded string found')
  - (185, 'Hardcoded string found')
  - (187, 'Line exceeds 80 characters')
  - (187, 'Hardcoded string found')
  - (190, 'Line exceeds 80 characters')
  - (192, 'Hardcoded string found')
  - (194, 'Line exceeds 80 characters')
  - (194, 'Hardcoded string found')
  - (202, 'Hardcoded string found')
  - (205, 'Line exceeds 80 characters')
  - (206, 'Line exceeds 80 characters')
  - (206, 'Hardcoded string found')
  - (217, 'Hardcoded string found')
  - (218, 'Hardcoded string found')
  - (221, 'Hardcoded string found')
  - (222, 'Hardcoded string found')
  - (226, 'Line exceeds 80 characters')
  - (226, 'Hardcoded string found')
  - (227, 'Line exceeds 80 characters')
  - (228, 'Line exceeds 80 characters')
  - (239, 'Line exceeds 80 characters')
  - (243, 'Hardcoded string found')
  - (244, 'Hardcoded string found')
  - (249, 'Hardcoded string found')
  - (250, 'Hardcoded string found')
  - (253, 'Line exceeds 80 characters')
  - (259, 'Line exceeds 80 characters')
  - (267, 'Hardcoded string found')
  - (268, 'Hardcoded string found')
  - (274, 'Hardcoded string found')
  - (275, 'Hardcoded string found')
  - (276, 'Line exceeds 80 characters')
  - (283, 'Hardcoded string found')
  - (294, 'Line exceeds 80 characters')
  - (294, 'Hardcoded string found')
  - (297, 'Line exceeds 80 characters')
  - (312, 'Line exceeds 80 characters')
  - (313, 'Line exceeds 80 characters')
  - (327, 'Hardcoded string found')
  - (328, 'Hardcoded string found')
  - (342, 'Hardcoded string found')
  - (346, 'Line exceeds 80 characters')
  - (346, 'Hardcoded string found')
  - (349, 'Hardcoded string found')
  - (351, 'Hardcoded string found')
  - (355, 'Line exceeds 80 characters')
  - (356, 'Line exceeds 80 characters')
  - (357, 'Hardcoded string found')
  - (358, 'Line exceeds 80 characters')
  - (358, 'Hardcoded string found')
  - (369, 'Hardcoded string found')
  - (376, 'Hardcoded string found')
  - (397, 'Line exceeds 80 characters')
  - (403, 'Hardcoded string found')
  - (408, 'Line exceeds 80 characters')
  - (408, 'Hardcoded string found')
  - (412, 'Line exceeds 80 characters')
  - (414, 'Line exceeds 80 characters')
  - (419, 'Line exceeds 80 characters')
  - (447, 'Line exceeds 80 characters')
  - (453, 'Line exceeds 80 characters')
  - (453, 'Hardcoded string found')
  - (465, 'Line exceeds 80 characters')
  - (467, 'TODO found')
  - (471, 'Hardcoded string found')
  - (475, 'Hardcoded string found')
  - (476, 'Line exceeds 80 characters')
  - (482, 'Hardcoded string found')
  - (487, 'Hardcoded string found')
  - (488, 'Hardcoded string found')
  - (489, 'Line exceeds 80 characters')
  - (492, 'Line exceeds 80 characters')
  - (492, 'Hardcoded string found')
  - (495, 'Hardcoded string found')
  - (503, 'Line exceeds 80 characters')
  - (504, 'Line exceeds 80 characters')
  - (504, 'Hardcoded string found')
  - (506, 'Line exceeds 80 characters')
  - (506, 'Hardcoded string found')
  - (508, 'Hardcoded string found')
  - (509, 'Line exceeds 80 characters')
Issues in src/tx-validator.ts:
  - (5, 'Hardcoded string found')
  - (29, 'Line exceeds 80 characters')
  - (32, 'Line exceeds 80 characters')
  - (36, 'Line exceeds 80 characters')
  - (37, 'Line exceeds 80 characters')
  - (45, 'Line exceeds 80 characters')
  - (50, 'Hardcoded string found')
  - (73, 'Hardcoded string found')
  - (74, 'Line exceeds 80 characters')
  - (74, 'Hardcoded string found')
  - (81, 'Line exceeds 80 characters')
  - (81, 'Hardcoded string found')
  - (97, 'Hardcoded string found')
  - (99, 'Hardcoded string found')
  - (100, 'Hardcoded string found')
  - (122, 'Hardcoded string found')
  - (125, 'Hardcoded string found')
  - (131, 'Line exceeds 80 characters')
  - (131, 'Hardcoded string found')
  - (135, 'Hardcoded string found')
  - (161, 'Hardcoded string found')
  - (162, 'Line exceeds 80 characters')
  - (162, 'Hardcoded string found')
  - (163, 'Hardcoded string found')
  - (172, 'Line exceeds 80 characters')
  - (172, 'Hardcoded string found')
  - (174, 'Hardcoded string found')
  - (175, 'Hardcoded string found')
  - (176, 'Hardcoded string found')
  - (177, 'Hardcoded string found')
  - (187, 'Hardcoded string found')
  - (211, 'Line exceeds 80 characters')
  - (211, 'Hardcoded string found')
  - (214, 'Hardcoded string found')
  - (235, 'Line exceeds 80 characters')
  - (244, 'Hardcoded string found')
  - (246, 'Hardcoded string found')
Issues in test/package.json:
  - (2, 'Hardcoded string found')
Issues in tsconfig.esm.json:
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
  - (10, 'Hardcoded string found')
  - (11, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
  - (13, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
  - (17, 'Hardcoded string found')
  - (18, 'Hardcoded string found')
  - (19, 'Hardcoded string found')
  - (21, 'Hardcoded string found')
  - (22, 'Hardcoded string found')
Issues in tsconfig.json:
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
  - (10, 'Hardcoded string found')
  - (11, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
  - (13, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
  - (17, 'Hardcoded string found')
  - (18, 'Hardcoded string found')
  - (19, 'Hardcoded string found')
  - (20, 'Hardcoded string found')
  - (21, 'Hardcoded string found')
  - (22, 'Hardcoded string found')
  - (23, 'Hardcoded string found')
  - (24, 'Hardcoded string found')
  - (25, 'Hardcoded string found')
  - (26, 'Hardcoded string found')
  - (27, 'Hardcoded string found')
  - (28, 'Hardcoded string found')
  - (29, 'Hardcoded string found')
  - (31, 'Hardcoded string found')
  - (32, 'Hardcoded string found')
  - (33, 'Hardcoded string found')
  - (34, 'Hardcoded string found')

**Comment by satomichru** [comment]
I got it.
