### ISSUE TITLE
Issue-Update tsconfig

### ISSUE THREAD

**Issue by scdnj** [scdnj/micro-signer-eth#228]
Automated Review Comments
Issues in tsconfig.esm.json:
  - (2, 'Hardcoded string found')
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
  - (10, 'Hardcoded string found')
  - (11, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
  - (13, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
  - (17, 'Hardcoded string found')
  - (18, 'Hardcoded string found')
  - (19, 'Hardcoded string found')
  - (20, 'Hardcoded string found')
  - (21, 'Hardcoded string found')
  - (22, 'Hardcoded string found')
  - (24, 'Hardcoded string found')
  - (25, 'Hardcoded string found')
  - (26, 'Hardcoded string found')
  - (28, 'Hardcoded string found')
  - (29, 'Hardcoded string found')
Issues in tsconfig.json:
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
  - (10, 'Hardcoded string found')
  - (11, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
  - (13, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
  - (17, 'Hardcoded string found')
  - (18, 'Hardcoded string found')
  - (19, 'Hardcoded string found')
  - (20, 'Hardcoded string found')
  - (21, 'Hardcoded string found')
  - (22, 'Hardcoded string found')
  - (23, 'Hardcoded string found')
  - (25, 'Hardcoded string found')
  - (26, 'Hardcoded string found')
  - (27, 'Hardcoded string found')

**Comment by satomichru** [comment]
I got it.
