### ISSUE TITLE
Issue-abi: improve tree-shaking

### ISSUE THREAD

**Issue by scdnj** [scdnj/micro-signer-eth#274]
Automated Review Comments
Issues in src/abi/common.ts:
  - (6, 'Hardcoded string found')
  - (8, 'Line exceeds 80 characters')
  - (21, 'Line exceeds 80 characters')
  - (24, 'Line exceeds 80 characters')
  - (24, 'Hardcoded string found')
  - (33, 'Hardcoded string found')
  - (35, 'Line exceeds 80 characters')
  - (38, 'Line exceeds 80 characters')
  - (38, 'Hardcoded string found')
Issues in src/abi/erc20.ts:
  - (7, 'Line exceeds 80 characters')
  - (7, 'Hardcoded string found')
Issues in src/abi/index.ts:
  - (9, 'Hardcoded string found')
  - (10, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
  - (13, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
  - (17, 'Hardcoded string found')
  - (18, 'Hardcoded string found')
  - (19, 'Hardcoded string found')
  - (32, 'Hardcoded string found')
  - (33, 'Hardcoded string found')
  - (35, 'Hardcoded string found')
  - (36, 'Hardcoded string found')
  - (37, 'Hardcoded string found')
  - (38, 'Hardcoded string found')
  - (39, 'Hardcoded string found')
  - (40, 'Hardcoded string found')
  - (41, 'Hardcoded string found')
  - (42, 'Hardcoded string found')
  - (52, 'Line exceeds 80 characters')
  - (53, 'Line exceeds 80 characters')
  - (53, 'Hardcoded string found')
  - (54, 'Line exceeds 80 characters')
  - (56, 'Line exceeds 80 characters')
  - (56, 'Hardcoded string found')
  - (60, 'Line exceeds 80 characters')
  - (61, 'Line exceeds 80 characters')
  - (61, 'Hardcoded string found')
  - (62, 'Line exceeds 80 characters')
  - (64, 'Line exceeds 80 characters')
  - (64, 'Hardcoded string found')
Issues in src/abi/kyber.ts:
  - (7, 'Line exceeds 80 characters')
  - (7, 'Hardcoded string found')
  - (18, 'Line exceeds 80 characters')
Issues in src/abi/uniswap-v2.ts:
  - (7, 'Line exceeds 80 characters')
  - (7, 'Hardcoded string found')
  - (18, 'Line exceeds 80 characters')
Issues in src/abi/uniswap-v3.ts:
  - (7, 'Line exceeds 80 characters')
  - (7, 'Hardcoded string found')
  - (11, 'Hardcoded string found')
  - (12, 'Line exceeds 80 characters')
  - (12, 'Hardcoded string found')
  - (13, 'Line exceeds 80 characters')
  - (15, 'Line exceeds 80 characters')
  - (24, 'Line exceeds 80 characters')
Issues in src/abi/weth.ts:
  - (7, 'Line exceeds 80 characters')
  - (7, 'Hardcoded string found')

**Comment by satomichru** [comment]
I got it.
