### ISSUE TITLE
Issue-Add support for eip1191

### ISSUE THREAD

**Issue by scdnj** [scdnj/micro-signer-eth#276]
Automated Review Comments
Issues in src/address.ts:
  - (16, 'Hardcoded string found')
  - (41, 'Line exceeds 80 characters')
Issues in src/tx.ts:
  - (3, 'Line exceeds 80 characters')
  - (24, 'Line exceeds 80 characters')
  - (25, 'Line exceeds 80 characters')
  - (25, 'Hardcoded string found')
  - (28, 'Hardcoded string found')
  - (41, 'Line exceeds 80 characters')
  - (46, 'Line exceeds 80 characters')
  - (46, 'Hardcoded string found')
  - (48, 'Line exceeds 80 characters')
  - (48, 'Hardcoded string found')
  - (49, 'Line exceeds 80 characters')
  - (49, 'Hardcoded string found')
  - (53, 'Line exceeds 80 characters')
  - (60, 'Line exceeds 80 characters')
  - (61, 'Line exceeds 80 characters')
  - (61, 'Hardcoded string found')
  - (64, 'Hardcoded string found')

**Comment by satokihanada** [comment]
I got it.
