### ISSUE TITLE
Issue-Bump packed

### ISSUE THREAD

**Issue by scdnj** [scdnj/micro-signer-eth#280]
Automated Review Comments
Issues in package-lock.json:
  - (2, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (11, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
  - (15, 'Line exceeds 80 characters')
  - (15, 'Hardcoded string found')
  - (16, 'Line exceeds 80 characters')
  - (16, 'Hardcoded string found')
  - (17, 'Hardcoded string found')
  - (18, 'Line exceeds 80 characters')
  - (18, 'Hardcoded string found')
  - (19, 'Line exceeds 80 characters')
  - (19, 'Hardcoded string found')
  - (20, 'Hardcoded string found')
Issues in package.json:
  - (2, 'Hardcoded string found')
  - (8, 'Hardcoded string found')

**Comment by satomichru** [comment]
I got it.
