### ISSUE TITLE
Issue-Fix fee calc. Add fee tests. Export more abis

### ISSUE THREAD

**Issue by scdnj** [scdnj/micro-signer-eth#286]
Automated Review Comments
Issues in src/abi/index.ts:
  - (3, 'Line exceeds 80 characters')
  - (6, 'Line exceeds 80 characters')
  - (12, 'Line exceeds 80 characters')
  - (12, 'Hardcoded string found')
  - (15, 'Line exceeds 80 characters')
Issues in src/index.ts:
  - (2, 'Line exceeds 80 characters')
  - (2, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
  - (20, 'Hardcoded string found')
  - (26, 'TODO found')
Issues in test/fee.test.js:
  - (7, 'Line exceeds 80 characters')
  - (9, 'Hardcoded string found')
  - (10, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
  - (28, 'Hardcoded string found')
  - (40, 'Line exceeds 80 characters')
  - (74, 'Line exceeds 80 characters')

**Comment by satokihanada** [comment]
I got it.
