### ISSUE TITLE
Issue-Fix

### ISSUE THREAD

**Issue by scdnj** [scdnj/micro-signer-eth#29]
Automated Review Comments
Issues in index.js:
  - (2, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
Issues in index.ts:
  - (1, 'Line exceeds 80 characters')
  - (2, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (7, 'Line exceeds 80 characters')
  - (7, 'Hardcoded string found')

**Comment by satomichru** [comment]
I got it.
