### ISSUE TITLE
Issue-Implement SSZ in 900 lines. Follow Deneb spec.

### ISSUE THREAD

**Issue by scdnj** [scdnj/micro-signer-eth#302]
Automated Review Comments
Issues in src/ssz.ts:
  - (12, 'Line exceeds 80 characters')
  - (13, 'Line exceeds 80 characters')
  - (19, 'Line exceeds 80 characters')
  - (32, 'Line exceeds 80 characters')
  - (44, 'Line exceeds 80 characters')
  - (71, 'Line exceeds 80 characters')
  - (76, 'Line exceeds 80 characters')
  - (82, 'Line exceeds 80 characters')
  - (90, 'Hardcoded string found')
  - (92, 'Hardcoded string found')
  - (93, 'Hardcoded string found')
  - (94, 'Hardcoded string found')
  - (95, 'Hardcoded string found')
  - (96, 'Hardcoded string found')
  - (126, 'Hardcoded string found')
  - (127, 'Hardcoded string found')
  - (153, 'Line exceeds 80 characters')
  - (156, 'Line exceeds 80 characters')
  - (157, 'Line exceeds 80 characters')
  - (175, 'Hardcoded string found')
  - (179, 'Line exceeds 80 characters')
  - (195, 'Hardcoded string found')
  - (201, 'Line exceeds 80 characters')
  - (207, 'Line exceeds 80 characters')
  - (214, 'Line exceeds 80 characters')
  - (232, 'Line exceeds 80 characters')
  - (237, 'Line exceeds 80 characters')
  - (240, 'Line exceeds 80 characters')
  - (246, 'Line exceeds 80 characters')
  - (248, 'TODO found')
  - (262, 'Line exceeds 80 characters')
  - (263, 'Line exceeds 80 characters')
  - (281, 'Line exceeds 80 characters')
  - (289, 'Line exceeds 80 characters')
  - (299, 'Line exceeds 80 characters')
  - (321, 'Line exceeds 80 characters')
  - (324, 'Line exceeds 80 characters')
  - (338, 'Line exceeds 80 characters')
  - (348, 'Line exceeds 80 characters')
  - (352, 'Line exceeds 80 characters')
  - (357, 'TODO found')
  - (373, 'Line exceeds 80 characters')
  - (375, 'Line exceeds 80 characters')
  - (382, 'Line exceeds 80 characters')
  - (394, 'Line exceeds 80 characters')
  - (427, 'Line exceeds 80 characters')
  - (437, 'Line exceeds 80 characters')
  - (458, 'TODO found')
  - (458, 'Line exceeds 80 characters')
  - (492, 'Line exceeds 80 characters')
  - (584, 'Line exceeds 80 characters')
  - (599, 'Line exceeds 80 characters')
  - (609, 'Line exceeds 80 characters')
  - (625, 'Line exceeds 80 characters')
  - (687, 'Line exceeds 80 characters')
  - (693, 'Line exceeds 80 characters')
  - (694, 'Line exceeds 80 characters')
  - (717, 'Line exceeds 80 characters')
  - (723, 'Line exceeds 80 characters')
  - (741, 'Line exceeds 80 characters')
  - (757, 'Line exceeds 80 characters')
  - (758, 'Line exceeds 80 characters')
  - (763, 'Line exceeds 80 characters')
Issues in test/ssz.test.js:
  - (7, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (11, 'Line exceeds 80 characters')
  - (12, 'Line exceeds 80 characters')
  - (14, 'TODO found')
  - (16, 'Line exceeds 80 characters')
  - (21, 'Hardcoded string found')
  - (28, 'Hardcoded string found')
  - (29, 'Line exceeds 80 characters')
  - (30, 'Line exceeds 80 characters')
  - (46, 'Line exceeds 80 characters')
  - (47, 'Line exceeds 80 characters')
  - (53, 'Hardcoded string found')
  - (96, 'Hardcoded string found')
  - (112, 'Hardcoded string found')
  - (127, 'Hardcoded string found')
  - (152, 'Hardcoded string found')
  - (160, 'Hardcoded string found')
  - (164, 'Hardcoded string found')
  - (165, 'Hardcoded string found')
  - (169, 'Hardcoded string found')
  - (173, 'Hardcoded string found')
  - (178, 'Hardcoded string found')
  - (198, 'Hardcoded string found')
  - (231, 'Hardcoded string found')
  - (235, 'Hardcoded string found')
  - (237, 'Line exceeds 80 characters')
  - (238, 'Line exceeds 80 characters')
  - (259, 'Line exceeds 80 characters')
  - (264, 'Hardcoded string found')
  - (265, 'Hardcoded string found')
  - (269, 'Hardcoded string found')
  - (315, 'Hardcoded string found')
  - (320, 'Line exceeds 80 characters')
  - (321, 'Line exceeds 80 characters')
  - (330, 'Line exceeds 80 characters')
  - (335, 'Line exceeds 80 characters')
  - (345, 'Line exceeds 80 characters')
  - (357, 'Line exceeds 80 characters')
  - (368, 'Line exceeds 80 characters')
  - (371, 'Line exceeds 80 characters')
  - (379, 'Line exceeds 80 characters')
  - (384, 'Line exceeds 80 characters')
  - (396, 'Hardcoded string found')
  - (398, 'Hardcoded string found')
  - (402, 'Hardcoded string found')
  - (404, 'Line exceeds 80 characters')
  - (405, 'Line exceeds 80 characters')
  - (417, 'Line exceeds 80 characters')
  - (440, 'Line exceeds 80 characters')
  - (471, 'Hardcoded string found')
  - (544, 'Hardcoded string found')
  - (549, 'Hardcoded string found')
  - (551, 'Hardcoded string found')
  - (555, 'Hardcoded string found')
  - (567, 'Line exceeds 80 characters')
  - (574, 'Hardcoded string found')
  - (575, 'Hardcoded string found')
  - (576, 'Hardcoded string found')
  - (580, 'Line exceeds 80 characters')
  - (587, 'Hardcoded string found')
  - (589, 'Hardcoded string found')
  - (598, 'Hardcoded string found')
  - (607, 'Hardcoded string found')
  - (608, 'Hardcoded string found')
  - (619, 'Hardcoded string found')
  - (623, 'Hardcoded string found')
  - (627, 'Line exceeds 80 characters')

**Comment by satokihanada** [comment]
I got it.
