### ISSUE TITLE
Issue-Move test vectors into one repo (#24)

### ISSUE THREAD

**Issue by scdnj** [scdnj/micro-signer-eth#309]
Automated Review Comments
Issues in .github/workflows/nodejs.yml:
  - (21, 'Hardcoded string found')
Issues in test/rlp.test.js:
  - (8, 'Line exceeds 80 characters')
Issues in test/tx.test.js:
  - (1, 'Line exceeds 80 characters')
  - (4, 'Line exceeds 80 characters')
  - (4, 'Hardcoded string found')
  - (5, 'Line exceeds 80 characters')
  - (5, 'Hardcoded string found')
  - (6, 'Line exceeds 80 characters')
  - (6, 'Hardcoded string found')

**Comment by satokihanada** [comment]
I got it.
