### ISSUE TITLE
Issue-Fix invalid nonce handling

### ISSUE THREAD

**Issue by scdnj** [scdnj/micro-signer-eth#33]
Automated Review Comments
Issues in index.js:
  - (4, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (13, 'Hardcoded string found')
  - (17, 'Hardcoded string found')
  - (20, 'Hardcoded string found')
  - (23, 'Hardcoded string found')
  - (24, 'Hardcoded string found')
  - (27, 'Hardcoded string found')
Issues in index.ts:
  - (3, 'Line exceeds 80 characters')
  - (4, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (11, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
  - (17, 'Hardcoded string found')
  - (20, 'Hardcoded string found')
  - (21, 'Hardcoded string found')
  - (24, 'Hardcoded string found')

**Comment by satomichru** [comment]
I got it.
