### ISSUE TITLE
Issue-update deps

### ISSUE THREAD

**Issue by scdnj** [scdnj/micro-signer-eth#35]
Automated Review Comments
Issues in package.json:
  - (2, 'Hardcoded string found')
  - (3, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
  - (11, 'Hardcoded string found')
  - (17, 'Hardcoded string found')

**Comment by satomichru** [comment]
I got it.
