### ISSUE TITLE
Issue-Add support for EIP1559, EIP2930 London and Berlin

### ISSUE THREAD

**Issue by scdnj** [scdnj/micro-signer-eth#52]
Automated Review Comments
Issues in examples/eth-vanity-address-generator.js:
  - (16, 'Line exceeds 80 characters')
  - (23, 'Line exceeds 80 characters')
  - (34, 'Line exceeds 80 characters')
Issues in examples/readme.js:
  - (11, 'Line exceeds 80 characters')
  - (16, 'Hardcoded string found')
  - (18, 'Line exceeds 80 characters')
  - (21, 'Line exceeds 80 characters')
  - (21, 'Hardcoded string found')
  - (26, 'Hardcoded string found')
  - (27, 'Hardcoded string found')
Issues in index.d.ts:
  - (14, 'Line exceeds 80 characters')
  - (14, 'Hardcoded string found')
  - (16, 'Line exceeds 80 characters')
  - (18, 'Line exceeds 80 characters')
  - (18, 'Hardcoded string found')
  - (19, 'Line exceeds 80 characters')
  - (19, 'Hardcoded string found')
  - (20, 'Line exceeds 80 characters')
  - (20, 'Hardcoded string found')
  - (21, 'Line exceeds 80 characters')
  - (22, 'Line exceeds 80 characters')
  - (23, 'Line exceeds 80 characters')
  - (56, 'Line exceeds 80 characters')
  - (58, 'Line exceeds 80 characters')
Issues in index.js:
  - (2, 'Hardcoded string found')
  - (5, 'Line exceeds 80 characters')
  - (6, 'Line exceeds 80 characters')
  - (10, 'Line exceeds 80 characters')
  - (23, 'Hardcoded string found')
  - (26, 'Hardcoded string found')
  - (56, 'Line exceeds 80 characters')
  - (64, 'Line exceeds 80 characters')
  - (64, 'Hardcoded string found')
  - (68, 'Line exceeds 80 characters')
  - (68, 'Hardcoded string found')
  - (69, 'Hardcoded string found')
  - (70, 'Line exceeds 80 characters')
  - (70, 'Hardcoded string found')
  - (71, 'Hardcoded string found')
  - (77, 'Line exceeds 80 characters')
  - (77, 'Hardcoded string found')
  - (78, 'Hardcoded string found')
  - (79, 'Hardcoded string found')
  - (81, 'Hardcoded string found')
  - (86, 'Hardcoded string found')
  - (88, 'Hardcoded string found')
  - (90, 'Hardcoded string found')
  - (92, 'Hardcoded string found')
  - (94, 'Hardcoded string found')
  - (96, 'Hardcoded string found')
  - (100, 'Hardcoded string found')
  - (101, 'Hardcoded string found')
  - (104, 'Hardcoded string found')
  - (112, 'Hardcoded string found')
  - (117, 'Hardcoded string found')
  - (126, 'Hardcoded string found')
  - (130, 'Hardcoded string found')
  - (133, 'Hardcoded string found')
  - (138, 'Hardcoded string found')
  - (142, 'Hardcoded string found')
  - (148, 'Line exceeds 80 characters')
  - (148, 'Hardcoded string found')
  - (151, 'Hardcoded string found')
  - (156, 'Line exceeds 80 characters')
  - (156, 'Hardcoded string found')
  - (161, 'Hardcoded string found')
  - (168, 'Hardcoded string found')
  - (169, 'Hardcoded string found')
  - (172, 'Hardcoded string found')
  - (174, 'Hardcoded string found')
  - (177, 'Hardcoded string found')
  - (178, 'Hardcoded string found')
  - (179, 'Hardcoded string found')
  - (185, 'Line exceeds 80 characters')
  - (187, 'Hardcoded string found')
  - (202, 'Line exceeds 80 characters')
  - (205, 'Hardcoded string found')
  - (206, 'Hardcoded string found')
  - (208, 'Hardcoded string found')
  - (214, 'Line exceeds 80 characters')
  - (214, 'Hardcoded string found')
  - (215, 'Hardcoded string found')
  - (217, 'Line exceeds 80 characters')
  - (230, 'Hardcoded string found')
  - (231, 'Hardcoded string found')
  - (234, 'Line exceeds 80 characters')
  - (236, 'Hardcoded string found')
  - (237, 'Hardcoded string found')
  - (238, 'Line exceeds 80 characters')
  - (248, 'Line exceeds 80 characters')
  - (253, 'Hardcoded string found')
  - (257, 'Line exceeds 80 characters')
  - (257, 'Hardcoded string found')
  - (262, 'Hardcoded string found')
  - (265, 'Hardcoded string found')
  - (280, 'Hardcoded string found')
  - (282, 'Hardcoded string found')
  - (293, 'Hardcoded string found')
  - (299, 'Line exceeds 80 characters')
  - (299, 'Hardcoded string found')
  - (343, 'Line exceeds 80 characters')
  - (343, 'Hardcoded string found')
  - (349, 'Line exceeds 80 characters')
  - (355, 'Line exceeds 80 characters')
  - (362, 'Hardcoded string found')
  - (367, 'Hardcoded string found')
  - (368, 'Line exceeds 80 characters')
  - (373, 'Hardcoded string found')
  - (386, 'Line exceeds 80 characters')
  - (386, 'Hardcoded string found')
  - (387, 'Line exceeds 80 characters')
  - (390, 'Hardcoded string found')
  - (393, 'Line exceeds 80 characters')
  - (398, 'Line exceeds 80 characters')
  - (400, 'Line exceeds 80 characters')
  - (402, 'Line exceeds 80 characters')
  - (402, 'Hardcoded string found')
  - (409, 'Line exceeds 80 characters')
  - (409, 'Hardcoded string found')
  - (411, 'Line exceeds 80 characters')
  - (411, 'Hardcoded string found')
  - (412, 'Line exceeds 80 characters')
  - (416, 'Hardcoded string found')
  - (417, 'Hardcoded string found')
  - (418, 'Hardcoded string found')
  - (419, 'Hardcoded string found')
Issues in index.ts:
  - (4, 'Line exceeds 80 characters')
  - (16, 'Hardcoded string found')
  - (18, 'Hardcoded string found')
  - (47, 'Line exceeds 80 characters')
  - (60, 'Line exceeds 80 characters')
  - (60, 'Hardcoded string found')
  - (62, 'Line exceeds 80 characters')
  - (65, 'Line exceeds 80 characters')
  - (65, 'Hardcoded string found')
  - (66, 'Hardcoded string found')
  - (68, 'Line exceeds 80 characters')
  - (68, 'Hardcoded string found')
  - (69, 'Hardcoded string found')
  - (84, 'Hardcoded string found')
  - (85, 'Hardcoded string found')
  - (88, 'Line exceeds 80 characters')
  - (90, 'Line exceeds 80 characters')
  - (92, 'Line exceeds 80 characters')
  - (113, 'Line exceeds 80 characters')
  - (114, 'Hardcoded string found')
  - (116, 'Line exceeds 80 characters')
  - (118, 'Line exceeds 80 characters')
  - (118, 'Hardcoded string found')
  - (119, 'Hardcoded string found')
  - (120, 'Hardcoded string found')
  - (132, 'Line exceeds 80 characters')
  - (136, 'Line exceeds 80 characters')
  - (136, 'Hardcoded string found')
  - (138, 'Line exceeds 80 characters')
  - (138, 'Hardcoded string found')
  - (140, 'Hardcoded string found')
  - (143, 'Line exceeds 80 characters')
  - (143, 'Hardcoded string found')
  - (144, 'Line exceeds 80 characters')
  - (144, 'Hardcoded string found')
  - (146, 'Hardcoded string found')
  - (148, 'Hardcoded string found')
  - (151, 'Hardcoded string found')
  - (152, 'Hardcoded string found')
  - (155, 'Hardcoded string found')
  - (161, 'Line exceeds 80 characters')
  - (161, 'Hardcoded string found')
  - (165, 'Hardcoded string found')
  - (174, 'Hardcoded string found')
  - (176, 'Line exceeds 80 characters')
  - (176, 'Hardcoded string found')
  - (180, 'Hardcoded string found')
  - (186, 'Hardcoded string found')
  - (188, 'Line exceeds 80 characters')
  - (188, 'Hardcoded string found')
  - (194, 'Line exceeds 80 characters')
  - (194, 'Hardcoded string found')
  - (197, 'Hardcoded string found')
  - (200, 'Line exceeds 80 characters')
  - (201, 'Line exceeds 80 characters')
  - (201, 'Hardcoded string found')
  - (204, 'Line exceeds 80 characters')
  - (206, 'Hardcoded string found')
  - (214, 'Hardcoded string found')
  - (215, 'Hardcoded string found')
  - (218, 'Hardcoded string found')
  - (219, 'Line exceeds 80 characters')
  - (219, 'Hardcoded string found')
  - (221, 'Hardcoded string found')
  - (222, 'Hardcoded string found')
  - (228, 'Line exceeds 80 characters')
  - (230, 'Line exceeds 80 characters')
  - (230, 'Hardcoded string found')
  - (231, 'Line exceeds 80 characters')
  - (232, 'Line exceeds 80 characters')
  - (243, 'Line exceeds 80 characters')
  - (247, 'Hardcoded string found')
  - (248, 'Hardcoded string found')
  - (253, 'Hardcoded string found')
  - (254, 'Hardcoded string found')
  - (257, 'Line exceeds 80 characters')
  - (263, 'Line exceeds 80 characters')
  - (271, 'Hardcoded string found')
  - (272, 'Hardcoded string found')
  - (278, 'Hardcoded string found')
  - (279, 'Hardcoded string found')
  - (280, 'Line exceeds 80 characters')
  - (287, 'Line exceeds 80 characters')
  - (287, 'Hardcoded string found')
  - (290, 'Line exceeds 80 characters')
  - (291, 'Line exceeds 80 characters')
  - (299, 'Line exceeds 80 characters')
  - (300, 'Line exceeds 80 characters')
  - (301, 'Line exceeds 80 characters')
  - (308, 'Hardcoded string found')
  - (309, 'Hardcoded string found')
  - (310, 'Hardcoded string found')
  - (311, 'Hardcoded string found')
  - (326, 'Hardcoded string found')
  - (330, 'Line exceeds 80 characters')
  - (330, 'Hardcoded string found')
  - (334, 'Hardcoded string found')
  - (336, 'Hardcoded string found')
  - (346, 'Line exceeds 80 characters')
  - (347, 'Line exceeds 80 characters')
  - (348, 'Hardcoded string found')
  - (349, 'Line exceeds 80 characters')
  - (349, 'Hardcoded string found')
  - (360, 'Hardcoded string found')
  - (367, 'Hardcoded string found')
  - (380, 'Line exceeds 80 characters')
  - (385, 'Hardcoded string found')
  - (391, 'Line exceeds 80 characters')
  - (392, 'Line exceeds 80 characters')
  - (416, 'Line exceeds 80 characters')
  - (416, 'Hardcoded string found')
  - (436, 'Line exceeds 80 characters')
  - (438, 'TODO found')
  - (442, 'Hardcoded string found')
  - (447, 'Hardcoded string found')
  - (448, 'Line exceeds 80 characters')
  - (454, 'Hardcoded string found')
  - (468, 'Line exceeds 80 characters')
  - (468, 'Hardcoded string found')
  - (469, 'Line exceeds 80 characters')
  - (473, 'Hardcoded string found')
  - (482, 'Line exceeds 80 characters')
  - (484, 'Line exceeds 80 characters')
  - (486, 'Hardcoded string found')
  - (493, 'Line exceeds 80 characters')
  - (493, 'Hardcoded string found')
  - (495, 'Line exceeds 80 characters')
  - (495, 'Hardcoded string found')
  - (496, 'Line exceeds 80 characters')
Issues in package.json:
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (5, 'Line exceeds 80 characters')
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
Issues in test/eip155.json:
  - (2, 'Hardcoded string found')
Issues in test/test.js:
  - (10, 'Line exceeds 80 characters')
  - (11, 'Line exceeds 80 characters')
  - (13, 'Line exceeds 80 characters')
  - (14, 'Line exceeds 80 characters')
  - (17, 'Line exceeds 80 characters')
  - (19, 'Line exceeds 80 characters')
  - (28, 'Hardcoded string found')
  - (29, 'Hardcoded string found')
  - (32, 'Hardcoded string found')
  - (33, 'Hardcoded string found')
  - (34, 'Hardcoded string found')
  - (39, 'Hardcoded string found')
  - (40, 'Hardcoded string found')
  - (41, 'Hardcoded string found')
  - (42, 'Hardcoded string found')
  - (45, 'Hardcoded string found')
  - (46, 'Hardcoded string found')
  - (47, 'Hardcoded string found')
  - (48, 'Hardcoded string found')
  - (51, 'Hardcoded string found')
  - (52, 'Hardcoded string found')
  - (53, 'Hardcoded string found')
  - (54, 'Hardcoded string found')
  - (55, 'Hardcoded string found')
  - (65, 'Hardcoded string found')
  - (66, 'Line exceeds 80 characters')
  - (66, 'Hardcoded string found')
  - (77, 'Line exceeds 80 characters')
  - (114, 'Hardcoded string found')
  - (121, 'Line exceeds 80 characters')
  - (131, 'Hardcoded string found')
  - (133, 'Line exceeds 80 characters')
  - (134, 'Line exceeds 80 characters')
  - (136, 'Line exceeds 80 characters')
  - (136, 'Hardcoded string found')
  - (137, 'Line exceeds 80 characters')
  - (145, 'Line exceeds 80 characters')
  - (146, 'Line exceeds 80 characters')
  - (146, 'Hardcoded string found')
  - (147, 'Line exceeds 80 characters')
  - (148, 'Hardcoded string found')
  - (159, 'Line exceeds 80 characters')
  - (166, 'Line exceeds 80 characters')
  - (167, 'Line exceeds 80 characters')
  - (182, 'Line exceeds 80 characters')
  - (186, 'Line exceeds 80 characters')
  - (202, 'Line exceeds 80 characters')
  - (212, 'Line exceeds 80 characters')
Issues in test/transactions.json:
  - (2, 'Hardcoded string found')
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (9, 'Hardcoded string found')

**Comment by satomichru** [comment]
I got it.
