### ISSUE TITLE
Issue-New fields

### ISSUE THREAD

**Issue by scdnj** [scdnj/micro-signer-eth#73]
Automated Review Comments
Issues in README.md:
  - (1, 'Line exceeds 80 characters')
  - (8, 'Line exceeds 80 characters')
Issues in index.js:
  - (2, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (30, 'Line exceeds 80 characters')
Issues in index.ts:
  - (6, 'Line exceeds 80 characters')
  - (6, 'Hardcoded string found')
  - (10, 'Line exceeds 80 characters')
  - (12, 'Line exceeds 80 characters')
  - (17, 'Line exceeds 80 characters')
  - (32, 'Line exceeds 80 characters')
  - (33, 'Line exceeds 80 characters')

**Comment by satokihanada** [comment]
I got it.
