### ISSUE TITLE
Issue-Default tx type is london now

### ISSUE THREAD

**Issue by scdnj** [scdnj/micro-signer-eth#79]
Automated Review Comments
Issues in README.md:
  - (10, 'Line exceeds 80 characters')
  - (23, 'Hardcoded string found')
  - (27, 'Line exceeds 80 characters')
  - (28, 'Line exceeds 80 characters')
  - (29, 'Line exceeds 80 characters')
  - (30, 'Hardcoded string found')
  - (31, 'Line exceeds 80 characters')
  - (32, 'Line exceeds 80 characters')
  - (33, 'Line exceeds 80 characters')
  - (34, 'Line exceeds 80 characters')
Issues in index.js:
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
Issues in index.ts:
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (5, 'Hardcoded string found')

**Comment by satomichru** [comment]
I got it.
