### ISSUE TITLE
Issue-Replace js-sha3 with noble-hashes

### ISSUE THREAD

**Issue by scdnj** [scdnj/micro-signer-eth#84]
Automated Review Comments
Issues in index.js:
  - (4, 'Line exceeds 80 characters')
  - (10, 'Line exceeds 80 characters')
  - (16, 'Line exceeds 80 characters')
  - (44, 'Hardcoded string found')
  - (45, 'Line exceeds 80 characters')
Issues in index.ts:
  - (14, 'Line exceeds 80 characters')
  - (15, 'Line exceeds 80 characters')
  - (24, 'Line exceeds 80 characters')
  - (32, 'Line exceeds 80 characters')
  - (33, 'Line exceeds 80 characters')
  - (41, 'Hardcoded string found')
  - (42, 'Line exceeds 80 characters')
Issues in package.json:
  - (2, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (10, 'Hardcoded string found')

**Comment by satokihanada** [comment]
I got it.
